name: checkbox_grouped
description: flutter widget that grouping checkbox, recuperate the actual selection,support multiple selection
version: 0.6.1+1
homepage: https://github.com/liodali/grouped_checkbox
authors:
  - Mohamed ali hamza <hamza.mohamedali93@gmail.com>


environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #uses-material-design: true
  assets:
    - packages/checkbox_grouped/assets/check.flr
    - packages/checkbox_grouped/assets/background_check.flr
